var sailors = [
    {
        id: "1",
        scoutName: "Sailor Mercury",
        japaneseName: "Ami Mizuno (水野 亜美)",
        englishName: "Amy Anderson",
        birthday: "September 10",
        transformation_phrase: "Mercury Power, Make Up!",
        powers: "Bubble Spray, Shine Aqua Illusion",
        description: "The Guardian of Water and Wisdom.",
        likes: "Reading, studying, chess, swimming, sandwiches",
        dislikes: "Heat, dishonesty, love letters",
        affiliation: "Sailor Guardians",
        guardianCat: true

    },
    {
        id: "2",
        scoutName: "Sailor Venus",
        japaneseName: "Minako Aino (愛野 美奈子)",
        englishName: "Mina Andrews",
        birthday: "October 22",
        transformation_phrase: "Venus Power, Make Up!",
        powers: "Crescent Beam, Love-Me Chain",
        description: "The Guardian of Love and Beauty.",
        likes: "Singing, casing after idols, playing volleyball, romance",
        dislikes: "Her mother, police officers, being alone, math class, injustice",
        affiliation: "Sailor Guardians",
        guardianCat: true
    },
    {
        id: "3",
        scoutName: "Sailor Moon",
        japaneseName: "Usagi Tsukino (月野 うさぎ)",
        englishName: "Serena Tsukino",
        birthday: "June 30",
        transformation_phrase: "Moon Prism Power, Make Up!",
        powers: "Moon Tiara Action, Moon Healing Escalation",
        description: "The main protagonist of the series.",
        likes: "Eating cake, comics/manga, sleeping, video games, home economics class",
        dislikes: "Math class, dentists, ghosts, carrots",
        affiliation: "Sailor Guardians",
        guardianCat: true
    },
    {
        id: "4",
        scoutName: "Sailor Mars",
        japaneseName: "Rei Hino (火野 レイ)",
        englishName: "Raye Hino",
        birthday: "April 17",
        transformation_phrase: "Mars Power, Make Up!",
        powers: "Fire Soul, Burning Mandala",
        description: "The Guardian of Fire and Passion.",
        likes: "Meditation, white Casablancas, singing, spiritualism, fugu",
        dislikes: "Canned asparagus, lack of discipline, television, negativity",
        affiliation: "Sailor Guardians",
        guardianCat: true
    },
    {
        id: "5",
        scoutName: "Sailor Jupiter",
        japaneseName: "Makoto Kino (木野 まこと)",
        englishName: "Lita Kino",
        birthday: "December 5",
        transformation_phrase: "Jupiter Power, Make Up!",
        powers: "Supreme Thunder, Jupiter Oak Evolution",
        description: "The Guardian of Thunder and Courage.",
        likes: "Cooking, color pink, gardening, martial arts, home economics class",
        dislikes: "Airplanes, romantic rejection, insects",
        affiliation: "Sailor Guardians",
        guardianCat: true
    },
    {
        id: "6",
        scoutName: "Sailor Saturn",
        japaneseName: "Hotaru Tomoe (土萠 ほたる)",
        englishName: "Hotaru Tomlinson",
        birthday: "January 6",
        transformation_phrase: "Saturn Crystal Power, Make Up!",
        powers: "Silence Glaive, Death Reborn Revolution",
        description: "The Guardian of Silence and Destruction.",
        likes: "Reading, japanese soba, collecting lamps, poetry, solitude, painting",
        dislikes: "Milk, violence, marathons, injustice, gym class",
        affiliation: "Sailor Guardians",
        guardianCat: true
    },
    {
        id: "7",
        scoutName: "Sailor Uranus",
        japaneseName: "Haruka Tenou (天王 はるか)",
        englishName: "Amara Tenou",
        birthday: "January 27",
        transformation_phrase: "Uranus Planet Power, Make Up!",
        powers: "World Shaking, Space Sword Blaster",
        description: "The Guardian of the Skies and Sky Scraper.",
        likes: "Racing, sports, color gold, salad, challenges",
        dislikes: "Unnecessary rules, weakness, modern history, Natto",
        affiliation: "Sailor Guardians",
        guardianCat: true
    },
    {
        id: "8",
        scoutName: "Sailor Neptune",
        japaneseName: "Michiru Kaiou (海王 みちる)",
        englishName: "Michel Kaiou",
        birthday: "March 6",
        transformation_phrase: "Neptune Planet Power, Make Up!",
        powers: "Deep Submerge, Submarine Reflection",
        description: "The Guardian of the Ocean and Intuition.",
        likes: "Collecting cosmetics, playing the violin, color marine blue, sashimi, music, swimming, the arts",
        dislikes: "Disorder, sea cucumbers, kikurage",
        affiliation: "Sailor Guardians",
        guardianCat: true
    }
]